services:
  backend:
    build: ./backend
    container_name: webtorrent-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - downloads:/app/downloads
    environment:
      - PORT=8080
      - TMDB_API_KEY=f91068b10bbe2b1a868e58d1fae6cbb4
    # Hardware acceleration support (VAAPI) - opcional
    devices:
      - /dev/dri:/dev/dri
    networks:
      - webtorrent-net

  frontend:
    build: ./frontend
    container_name: webtorrent-frontend
    restart: unless-stopped
    ports:
      - "5175:80"
    depends_on:
      - backend
    networks:
      - webtorrent-net

volumes:
  downloads:

networks:
  webtorrent-net:
    driver: bridge
